name = "daily-journal-card"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "daily-journal-card-db"
database_id = "07ce2f73-d780-44b2-937c-0fc87f2c5b38"
